# Generated by Django 3.2 on 2023-04-20 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=30)),
                ('contact_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='usertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('emailid', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=30)),
                ('rpassword', models.CharField(blank=True, max_length=30, null=True)),
                ('phoneno', models.CharField(default=None, max_length=13)),
                ('licence_no', models.CharField(default=None, max_length=50)),
                ('address', models.CharField(default=None, max_length=500)),
                ('role', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=40)),
                ('vehicle_color', models.CharField(max_length=40)),
                ('vehicle_number', models.CharField(max_length=40)),
                ('vehicle_type', models.CharField(max_length=40)),
                ('vehicle_location', models.CharField(default='None', max_length=20)),
                ('rent_per_day', models.CharField(max_length=40)),
                ('vehicle_photo', models.ImageField(upload_to='photos')),
                ('vehicle_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ratings', models.CharField(max_length=25)),
                ('comments', models.CharField(max_length=50)),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='booking_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_duration', models.DateField()),
                ('from_to', models.DateField()),
                ('amount', models.CharField(max_length=30)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('paystatus', models.BooleanField(default=False)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.usertable')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.vehicle_table')),
            ],
        ),
    ]
