# Generated by Django 3.2 on 2023-04-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='address',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='licence_no',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='phoneno',
        ),
        migrations.AddField(
            model_name='usertable',
            name='addres',
            field=models.CharField(default='Doest Have', max_length=500),
        ),
        migrations.AddField(
            model_name='usertable',
            name='licence',
            field=models.CharField(default='123', max_length=50),
        ),
        migrations.AddField(
            model_name='usertable',
            name='phonen',
            field=models.CharField(default='123', max_length=13),
        ),
    ]
