# Generated by Django 3.2 on 2023-04-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0002_auto_20230420_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='image',
            field=models.CharField(default='/media/hello.jpg', max_length=60),
        ),
    ]
