# Generated by Django 3.2 on 2023-04-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0003_usertable_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_table',
            old_name='paystatus',
            new_name='status',
        ),
    ]
